### ISSUE TITLE
Python dependency missing

### ISSUE THREAD

**Issue by HakimEG** [makinbacon21/switchroot-script-builder#1]
Hi there,

I ran into an error running this after spinning a new WSL instance of Ubuntu up.

You should probably include Python as a dependency - it also breaks the script in generel, if ran without python, since you need to do some cleanup (aka remove android folder and such), since repo init only happens if the android folder isnt present :)

**Comment by Jamiexhz** [comment]
And repo doesn't seem to be installed properly on my end (Ubuntu 20.10). Command-not-found error occured after auto installation.   
It's also recommended to add auto clean-up option in the script.

**Comment by makinbacon21** [comment]
@HakimEG I will include Python--btw WSL is not supported, I should add that to README. WSL 2 technically works but you have to enable NTFS case sensitivity manually on the ./android tree which is not built into the script. Idek if it's possible but I will look into it...maybe I'll write a PS script to invoke this script or add a flag or smth. Thanks for letting me know!

**Comment by makinbacon21** [comment]
@Jamiexhz I'm not sure what you mean...the script should just work if you clone the repo, `chmod +x` the script, and run the command in bash from the folder.

**Comment by Jamiexhz** [comment]
> @Jamiexhz I'm not sure what you mean...the script should just work if you clone the repo, `chmod +x` the script, and run the command in bash from the folder.

I've submitted a new issue to clarify the situation.
