### ISSUE TITLE
Reporting Compatibility Issues

### ISSUE THREAD

**Issue by Jamiexhz** [makinbacon21/switchroot-script-builder#2]
Hi there,  
Thanks for all your work to make the compiling progress simple and straight forward. I've met some compatibility issue using the script, which are listed as below:  
*Compile environment:  
Ubuntu 20.04  X64  
Clean install  - No other dependencies or software installed previously.  
Using the most recent version of the script.*
  
**1. Lack of dependencies**  
    Errors:
     `./Q_Builder.sh: line 14: lib32ncurses5-dev: command not found`  
     `./Q_Builder.sh: line 15: libssl-dev: command not found`  
     `./Q_Builder.sh: line 16: zlib1g-dev: command not found`  
     `./Q_Builder.sh: line 83: unzip: command not found`  
    Python seems to be not installed as well.
    I'm not sure why this happened, but it seems that by putting all the variables into one line could solve the problem.  
     `sudo apt install bc bison ... qemu-user-static`  
    Instead of
     `sudo apt install bc ...`  
     ` > imagemagick ...`
  
**2. Paths not added**  
    Errors:
     `./Q_Builder.sh: line 87: [: too many arguments`    
     `./Q_Builder.sh: line 108: [: too many arguments`  
    Solved after manually added path and did ` source ~/.profile ` (which seem to be lacked in the script).  
  
**3.  Suggestions**  
  + Add `apt-get update` before installing dependencies.
  + Add auto cleanup option so users who messed up somehow could simply restore to previous status and retry.

**Comment by makinbacon21** [comment]
Lolll I should (and will) add apt-get update before dependencies. The one line thing is irrelevant as separating it like that should not impact execution. Python has been added as a dependency as of the other day. As far as the arguments part, that particular section is being worked on--thank you for the feedback!
