### ISSUE TITLE
Add more options to Q_Builder.sh

### ISSUE THREAD

**Issue by EmmmaTech** [makinbacon21/switchroot-script-builder#3]
In the command line, there should be more options you can use. A few I think should be included are -g for not downloading OpenGApps and -h for not downloading Hekate. If people already have Hekate and/or they aren't planning to use OpenGApps, this should be useful.

**Comment by makinbacon21** [comment]
true--i think kage put it in his pr so ill take a look at that first, but if not ill certainly add it

**Comment by makinbacon21** [comment]
yes this will be fixed in next update--it'll be a y/n question at the beginning of the script

**Comment by EmmmaTech** [comment]
Yeah thank you!
